# Generated by Django 2.0.2 on 2018-02-19 22:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projections', '0004_auto_20180219_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batterprojection',
            name='pos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='battervalue',
            name='pos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='pitcherprojection',
            name='pos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='pitchervalue',
            name='pos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, default=list, size=None),
        ),
    ]
