# Generated by Django 2.0.2 on 2018-02-06 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yahooGuid', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('access_token', models.CharField(max_length=200)),
                ('token_expiration', models.DateTimeField()),
                ('refresh_token', models.CharField(max_length=200)),
                ('main_league', models.CharField(max_length=200)),
                ('leagues', models.ManyToManyField(to='leagues.League')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
