# Generated by Django 2.0.2 on 2018-02-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='access_token',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='leagues',
            field=models.ManyToManyField(blank=True, to='leagues.League'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='main_league',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='token_expiration',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='yahooGuid',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
