# Generated by Django 2.0.2 on 2018-02-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_auto_20180206_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
