# Generated by Django 2.0.2 on 2018-02-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0005_auto_20180206_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='access_token',
            field=models.TextField(blank=True),
        ),
    ]
