# Generated by Django 2.0.2 on 2018-02-20 14:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0009_auto_20180216_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='batting_pos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='league',
            name='bench_pos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='league',
            name='dl_pos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='league',
            name='na_pos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='league',
            name='pitcher_pos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, default=list, size=None),
        ),
    ]
