# Generated by Django 2.0.2 on 2018-02-20 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0010_auto_20180220_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='prev_year_league',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='leagues.League'),
        ),
    ]
